name: carbon_counter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-24.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.3.0
  gsheets: ^0.5.0
  syncfusion_flutter_charts: ^23.1.41
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
