name: carbon_counter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  intl: ^0.18.1
  timezone: ^0.10.0
  fl_chart: ^0.68.0
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.3.0
  gsheets: ^0.5.0
  syncfusion_flutter_charts: ^23.1.41
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
